/*DOM:Structured representation of html documents .Allows JS to access
html elements and styles to manipulate them.
Tree structured, generated by browser on html load
Document:special object that is the entry point to DOM. eg.document.querySelector()
DOM is not the part of JS, it is the part of WEB API
*/

